import express from 'express';
import dotenv from 'dotenv';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import morgan from 'morgan';
import { connectDB } from './config/db.js';
import apiRoutes from './routes/index.js';
import { notFound, errorHandler } from './middleware/errorMiddleware.js';

dotenv.config();
await connectDB();
const app = express();
app.use(helmet());
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173', credentials:true }));
app.use(express.json({ limit:'2mb' }));
app.use(morgan('dev'));
app.use(rateLimit({ windowMs: 15*60*1000, max: 300, standardHeaders:true, legacyHeaders:false }));
app.get('/', (req,res)=>res.json({ success:true, message:'AquaFarm Ledger API running' }));
app.use('/api', apiRoutes);
app.use(notFound);
app.use(errorHandler);
const port = process.env.PORT || 5000;
app.listen(port, ()=>console.log(`AquaFarm Ledger API running on port ${port}`));
