import express from 'express';
import authRoutes from './authRoutes.js';
import pondRoutes from './pondRoutes.js';
import batchRoutes from './batchRoutes.js';
import feedRoutes from './feedRoutes.js';
import waterRoutes from './waterRoutes.js';
import mortalityRoutes from './mortalityRoutes.js';
import harvestRoutes from './harvestRoutes.js';
import costRoutes from './costRoutes.js';
import alertRoutes from './alertRoutes.js';
import reportRoutes from './reportRoutes.js';
import settingsRoutes from './settingsRoutes.js';
const router = express.Router();
router.use('/auth', authRoutes);
router.use('/ponds', pondRoutes);
router.use('/batches', batchRoutes);
router.use('/feed-logs', feedRoutes);
router.use('/water-quality', waterRoutes);
router.use('/mortality', mortalityRoutes);
router.use('/harvests', harvestRoutes);
router.use('/costs', costRoutes);
router.use('/alerts', alertRoutes);
router.use('/reports', reportRoutes);
router.use('/settings', settingsRoutes);
export default router;
