import React from 'react';
import { useEffect, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '../services/api';
import { AlertBanner, DashboardCard, LoadingSpinner, PageHeader, StatusBadge, Card } from '../components/ui';
import { BadgeDollarSign, BellRing, Droplets, FishSymbol, Skull, Waves, Wheat, ClipboardList } from 'lucide-react';
const money=(n)=>`LKR ${Number(n||0).toLocaleString()}`;
export default function Dashboard(){const [data,setData]=useState(null); useEffect(()=>{api.get('/reports/dashboard').then(r=>setData(r.data.data))},[]); if(!data)return <LoadingSpinner/>; const s=data.stats; return <><PageHeader title="Farm Command Dashboard" subtitle="Realtime overview of ponds, fish stock, water quality, feed, cost and harvest health."/><AlertBanner>{data.alerts?.[0]?.message || 'No critical alerts. Farm operation looks stable.'}</AlertBanner><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><DashboardCard title="Total Ponds" value={s.totalPonds} icon={Waves} sub="Active farm units"/><DashboardCard title="Active Batches" value={s.activeBatches} icon={FishSymbol} sub="Growing and harvest-ready"/><DashboardCard title="Total Stock" value={s.totalStock.toLocaleString()} icon={ClipboardList} sub="Current live stock"/><DashboardCard title="Today Feed" value={`${s.todayFeed}kg`} icon={Wheat} sub="Logged feed usage"/><DashboardCard title="Mortality Rate" value={`${s.mortalityRate}%`} icon={Skull} sub="Recorded recent rate" color="text-red-500"/><DashboardCard title="Water Score" value={`${s.waterQualityScore}/100`} icon={Droplets} sub="Average quality" color="text-aqua"/><DashboardCard title="Harvest Value" value={money(s.estimatedHarvestValue)} icon={BadgeDollarSign} sub="Estimated revenue"/><DashboardCard title="Monthly Cost" value={money(s.monthlyCost)} icon={BellRing} sub="Current month spend"/></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><Chart title="Water Quality Trend" data={data.charts.waterTrend} type="area" dataKey="score"/><Chart title="Feed Usage" data={data.charts.feedUsage} type="bar" dataKey="kg"/><Chart title="Mortality Trend" data={data.charts.mortalityTrend} type="bar" dataKey="deaths"/><Chart title="Harvest Forecast" data={data.charts.harvestForecast} type="area" dataKey="revenue"/></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Card><h3 className="mb-4 text-xl font-black">Recent Alerts</h3><div className="space-y-3">{data.alerts.map(a=><div key={a._id} className="flex items-center justify-between rounded-2xl bg-white p-4"><div><p className="font-bold">{a.title}</p><p className="text-sm text-slate-500">{a.message}</p></div><StatusBadge type={a.status}>{a.severity}</StatusBadge></div>)}</div></Card><Card><h3 className="mb-4 text-xl font-black">Upcoming Harvests</h3><div className="space-y-3">{data.harvests.slice(0,5).map(h=><div key={h._id} className="flex items-center justify-between rounded-2xl bg-white p-4"><div><p className="font-bold">{h.batch?.batchName}</p><p className="text-sm text-slate-500">{new Date(h.expectedHarvestDate).toLocaleDateString()}</p></div><b>{money(h.estimatedRevenue)}</b></div>)}</div></Card></div></>}
function Chart({title,data,type,dataKey}){return <Card><h3 className="mb-4 text-xl font-black">{title}</h3><div className="h-72"><ResponsiveContainer>{type==='bar'?<BarChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey={dataKey} fill="#7C3AED" radius={[12,12,0,0]}/></BarChart>:<AreaChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Area type="monotone" dataKey={dataKey} stroke="#7C3AED" fill="#7C3AED33"/></AreaChart>}</ResponsiveContainer></div></Card>}
